# SwiftLint Configuration for TotalSegmentator Horos Plugin
# https://realm.github.io/SwiftLint/

# Paths to include/exclude
included:
  - MyOsiriXPluginFolder-Swift

excluded:
  - Pods
  - MyOsiriXPluginFolder-Swift/Horos.framework
  - .build

# Disabled rules
disabled_rules:
  - trailing_whitespace
  - todo  # Allow TODO comments for now

# Opt-in rules (not enabled by default)
opt_in_rules:
  - empty_count
  - empty_string
  - explicit_init
  - first_where
  - force_unwrapping
  - implicitly_unwrapped_optional
  - literal_expression_end_indentation
  - modifier_order
  - multiline_arguments
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_first_last
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call

# Rule configurations
line_length:
  warning: 150
  error: 200
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true

file_length:
  warning: 500
  error: 1000
  ignore_comment_only_lines: true

function_body_length:
  warning: 60
  error: 100

type_body_length:
  warning: 300
  error: 500

cyclomatic_complexity:
  warning: 15
  error: 25
  ignores_case_statements: true

nesting:
  type_level:
    warning: 2
  statement_level:
    warning: 5

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - x
    - y
    - z
    - i
    - j
    - k
    - r
    - g
    - b
    - a

type_name:
  min_length:
    warning: 3
    error: 2
  max_length:
    warning: 50
    error: 60

# Reporter type
reporter: "xcode"

# Custom rules
custom_rules:
  multiple_empty_lines:
    name: "Multiple Empty Lines"
    regex: '(\n\s*\n){3,}'
    message: "There should be no more than two consecutive empty lines."
    severity: warning

  force_cast_warning:
    name: "Force Cast Warning"
    regex: '\s+as!\s+'
    message: "Force casting should be avoided. Consider using 'as?' or guard let."
    severity: warning
